sudo: false

git:
  submodules: false

branches:
  only:
    - master

install:
  - .ci/download-hugo.sh
  - export PATH=$PATH:$PWD/.ci
  - hugo version

script:
  - git submodule update --init themes
  - hugo

deploy:
  provider: pages
  localdir: public
  branch: master
  verbose: true
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
