sudo: false

git:
  submodules: false

branches:
  only:
    - master

install:
  - .ci/download-hugo.sh
  - export PATH=$PATH:$PWD/.ci
  - hugo version

script:
  - git submodule update --init themes
  - hugo

deploy:
  provider: script
  script: bash .ci/publish.sh
